export const titles = {
  trending: [
    "Quantum Computing: The Most Disruptive Tech of the Decade",
    "Mixed Reality (MR): The Future of Human-Computer Interaction",
    "Edge Computing: Why Companies Are Adopting It Fast",
    "Autonomous AI Agents: The New Workforce of the Future",
    "Blockchain Beyond Crypto: Real Applications You Should Know",
    "6G Networks: What the Next Generation of Connectivity Brings",
    "Biohacking & Human Augmentation: Reimagining Human Potential",
    "Green Tech: Sustainable Innovation for a Better Future",
    "Smart Cities: How IoT Is Transforming Urban Living",
    "Robotics in 2025: The Rise of Humanoid and Assistive Robots",
  ],
  "ui ux": [
    "The Evolution of UI/UX: From Skeuomorphic to Neumorphism",
    "UX Research 101: Essential Methods for Beginners",
    "Dark Mode vs Light Mode: Which Truly Enhances Usability?",
    "Microinteractions: Small Details That Transform User Experience",
    "Top UI Design Trends to Watch in 2025",
    "Design Thinking: A Problem-Solving Framework for Creators",
    "Visual Hierarchy Principles: Designing with Clarity and Purpose",
    "Why Wireframes Matter: The Foundation of Every Interface",
    "Using Color Psychology to Improve Your UI",
    "Accessibility in Digital Design: A Must-Have in 2025",
  ],
  "software development": [
    "Waterfall vs Agile: Choosing the Right Approach for Your Project",
    "SOLID Principles: The Core of Modern Software Engineering",
    "Clean Code: How to Write Readable and Maintainable Code",
    "Version Control Best Practices Every Developer Should Know",
    "Pair Programming: Benefits and When to Apply It",
    "Test-Driven Development (TDD): Still Relevant in 2025?",
    "Refactoring: Improving Code Without Changing Its Behavior",
    "Why Modular Architecture Matters in Scalable Projects",
    "DRY vs WET Code: Understanding the Balance",
    "Essential Debugging Techniques for Developers",
  ],
  "web technologies": [
    "The Evolution of HTML: From HTML1 to the Modern Web",
    "What Is WebAssembly? The Future of High-Performance Web Apps",
    "REST API vs GraphQL: When to Use Each",
    "The Rise of JavaScript Frameworks in 2025",
    "Server-Side Rendering vs Client-Side Rendering: Which Is Better?",
    "Understanding HTTP/3: The Next Big Upgrade for the Web",
    "Progressive Web Apps: Building Web Experiences That Feel Native",
    "Web Performance Optimization: Speed Up Your Site in 2025",
    "Modern CSS: Flexbox, Grid, and the New CSS Features You Should Know",
    "Web Security Basics: Protecting Your Site from Common Attacks",
  ],
  devops: [
    "What Is DevOps? A Beginner-Friendly Overview",
    "CI/CD Explained: Automating Your Development Pipeline",
    "Infrastructure as Code (IaC): Tools and Concepts You Must Know",
    "Observability vs Monitoring: What's the Difference?",
    "Kubernetes 101: The Basics of Container Orchestration",
    "GitOps: The Future of Infrastructure Management",
    "How to Handle Incidents Efficiently as a DevOps Engineer",
    "Cloud-Native Development: Best Practices for 2025",
    "DevSecOps: Embedding Security into Every Stage of Development",
    "Blue-Green Deployment vs Canary Releases: When to Use Each Strategy",
  ],
  "machine learning": [
    "What Is Machine Learning? The Simplest Explanation You'll Find",
    "Supervised vs Unsupervised Learning: Key Differences",
    "The Evolution of AI Models: From GPT-1 to GPT-5",
    "Overfitting vs Underfitting: Common ML Pitfalls",
    "How Neural Networks Actually Work (Beginner-Friendly)",
    "Building High-Quality Datasets for Machine Learning",
    "Computer Vision: The Technology Behind Facial Recognition",
    "Natural Language Processing: How Machines Understand Language",
    "Reinforcement Learning: The AI Behind Robotics and Game Agents",
    "AI Ethics 2025: Understanding Bias in Machine Learning Models",
  ],
};